name: Pruebas unitarias automáticas
run-name: ${{ github.actor }} está ejecutando pruebas unitarias
on: [push, pull_request]
jobs:
  pruebas_unitarias_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: npm install
        working-directory: ./backend
      - name: Validar typescript
        run: npm run type-check
        working-directory: ./backend
      - name: Correr pruebas
        run: npm run test
        working-directory: ./backend

  pruebas_unitarias_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: npm install
        working-directory: ./frontend
      - name: Correr pruebas
        run: npm run test
        working-directory: ./frontend

